name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - mlflow
      - dagshub
      - joblib
      - scikit-learn
      - matplotlib
      - scikit-optimize
